classdef CLASS_DETECT_INTERFACE_Detection < handle
    
    properties
        DetectionConfig=[];
    end
    
    properties (SetAccess = protected, GetAccess = public)
        Detection=struct(...
            'Id',{},...
            'ROI', {},...
            'Centroid', {},...
            'Radius',{},...
            'Area', {},...
            'Orientation', {},...
            'MajorAxisLength', {},...
            'MinorAxisLength', {},...
            'ConvexHull', {},...
            'Mask',{});
        DetectionMask=[];
        DetectionMap=[];
    end
    
    methods (Abstract)
        Detect(obj);
    end
end