%   This file is a demo of UMUTracker Project.The UMUTracker is currently under active development.
%	Related information can be found in the paper :
%
%	Hanqing Zhang, Tim Stangner, Krister Wiklund, Alvaro Rodriguez, Magnus Andersson
%	UmUTracker: A versatile MATLAB program for automated particle tracking of 2D light microscopy or 3D digital holography data
%
%	We welcome comments and contributions to the documentation and code of UMUTracker to help us improve the implementation.
%
%   Version: 1.Initial version:  Hanqing Zhang,hanqing.zhang@umu.se
%
classdef CLASS_TRACK_INTERFACE_Tracking < handle
    properties
       TrackingConfig=[]; 
    end
    
    properties (SetAccess = public, GetAccess = public)
       Tracks = struct('Id', {},...
            'Valid',{},...
            'Centroid', {},...
            'Radius',{},...
            'ZPos',{},...
            'PredictedCentroid',{},...
            'FirstVisible', {},...
            'LastVisible',  {},...
            'Template',{},...
            'TemplateCenter',{},...
            'Features', {},...
            'Kalman',{},...
            'Age', {},...
            'TotalVisibleCount', {},...
            'Visibility',{},...
            'TotalVisibleNonOccludedCount', {},...
            'ConsecutiveInvisibleCount', {},...
            'ConsecutiveOccludedCount', {});
        AvailableTracksList=[];
        NextID=[];
    end
    
    methods (Abstract)
        Track(obj);
        ResetTracks(obj);
    end
end