function Func_ShowText(axes,Message)
    delete(get(axes,'Child'));
    text(0.5, 0.5,Message, ...
            'HorizontalAlignment', 'center', ...
            'Parent',axes,...
            'FontUnits', 'Normalized', ...
            'FontSize', 0.7 );
end